name: api-trigger-action

on:
  repository_dispatch:
    types: [hello]

jobs:
  api-trigger-action:
    runs-on: ubuntu-latest
    steps:
      - name:
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo "MESSAGE $MESSAGE"
      - name:
        env:
          EMAILS: ${{ github.event.client_payload.emails }}
        run: echo "EMAILS $EMAILS"
