name: api-trigger-action

on:
  repository_dispatch:
    types: [hello]

jobs:
  api-trigger-action:
    runs-on: ubuntu-latest
    steps:
      - name:
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo "MESSAGE $MESSAGE"
      - name:
        env:
          EMAILS: ${{ github.event.client_payload.emails }}
        run: echo "EMAILS $EMAILS"

# example: api
# curl \
#   -X POST \
#   -H "Accept: application/vnd.github+json" \
#   -H "Authorization: Bearer ${PAT}" \
#   https://api.github.com/repos/Wei18/demo-release-action/dispatches \
#   -d '{"event_type":"hello","client_payload":{"message":"測試","emails":"wei.cao@pinkoi.com"}}'
# result url: https://github.com/Wei18/demo-release-action/actions/runs/3051714485/jobs/4920269795
