name: CI-workflow-release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10, 4.6.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        # id: create_release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
      # - uses: eregon/publish-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     release_id: ${{ steps.create_release.outputs.id }}

  comment-on-pr:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            Release {release_link} here.