name: PR is up-to-date
on:
  pull_request_target:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Handle pull request
        if: github.event_name == 'pull_request_target'
        uses: Automattic/action-pr-is-up-to-date@v2
